#index:
#    path: /
#    controller: App\Controller\DefaultController::index

not_found:
    path: '{any}'
    controller: App\Controller\NotFoundController::notFound
    requirements:
        any: .*
